### ISSUE TITLE
Can't refuse to save

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#245]
I wanted to discard a scratch design and build a new one, so I clicked "create a new part".
The dialogue asks if I want to save my changes, I say "No", and it treats it instead as Cancel.

**Comment by cjmyers** [comment]
This one is clearly a but and should be fixed before the 3.0 release.

**Comment by michael13162** [comment]
I think this has already been fixed, but the prerelease wasn't updated.  I will check later today.

**Comment by cjmyers** [comment]
Your correct.  This is working for me on master.  Likely did not get into the latest Jar that we posted.

**Comment by jakebeal** [comment]
Still broken.   Make a document, put some stuff in, make a new document, "no" and it starts making me "Save As" anyway.

**Comment by cjmyers** [comment]
@michael13162 please have another looks at this one before the release.  Hopefully it is a simple fix.

**Comment by michael13162** [comment]
Ah, I understand what you mean.  The "save" dialog that pops up is actually meant to ask for where you want to save this new document that we're currently creating (since you pressed the make a new document button, it has to first know where the document is supposed to go).  With new part creation, this isn't necessary because parts are implied to go into the working document.  With new document creation, it has to first get an association with a location on disk.

To prevent confusion in the future, I've added a prompt that asks the user to "Please select a file to save the new SBOL Document into."  After clicking OK, the save dialog opens.  This should clear things up.

**Comment by cjmyers** [comment]
Creating a new document does not need to actually connect this with a filename on disk.  It should be just like when you open from scratch and give you a new untitled document to work in.

**Comment by michael13162** [comment]
Creating a new document now doesn't ask you to connect to a filename on disk.
