### ISSUE TITLE
Problems loading SBOL files and repository downloads

### ISSUE THREAD

**Issue by MadraghRua** [SynBioDex/SBOLDesigner#257]
HI Folks
I very recently downloaded SBOLDesigner. I am running the latest Java. I am on a Mac running High Sierra.

I've been using SBOLDesigner to query repositories for Parts and Designs. However when I go to load the design I get the error message  - Error reading SBOL. This is repeatable for the Synbiohub, LCP SynBioHub and the CIDARLab.

I also generated an SBOL file from a downloaded GenBank file. This was done through the SBOL GenBank to SBOL converter. This generates the following error:
org.sbolstandard.core2.SBOLValidationException: sbol-10105: An SBOL document MUST be serialized as a well-formed RDF/XML file that adheres to the grammar defined by: “https://www.w3.org/TR/rdf-syntax-grammar/” 
Reference: SBOL Version 2.2.0 Section 10 on page 58

I am able to get these parts downloaded from the repositories and imported into iBioSim. Not sure if that helps in any way.

Please let me know if you need more information. I have been intending to use SBOLDesigner in the SEED demo in two weeks, so please do let me know if I can do anything to help get this resolved.

Thanks
kevin

**Comment by cjmyers** [comment]
Please let us know OS and Java version.  I think this relates to an issue with Java 10 and an issue that may have been fixed in later libSBOLj snapshot.  We might need to create a new version of SBOLDesigner using the latest libSBOLj SNAPSHOT to see if this sorts this out @michael13162.

Chris

**Comment by MadraghRua** [comment]
The OS is High Sierra. The Java is 10.0.1

**Comment by MadraghRua** [comment]
As soon as you have something ping me on my emails - kpclancy@hotmail.com and madraghrua160@gmail.com. I'm putting together demos using iBioSim but if you can get SBOLDesigner patched for this version of Java then I will use that instead.

**Comment by MadraghRua** [comment]
Not sure if this is related but fIltering for a given part is also not working. So I can't type BBa_R0040 into the Filter parts box and get the part. I can do this in iBioSim but not in SBOLDesigner.
I can browse through the repositories by selecting and clicking but importing the part still doesn't work.

**Comment by cjmyers** [comment]
I'm pretty sure this is a Java 10 issue.  We have some issues with libSBOLj on Java 10, but I think we might have a way to sort them out.  Will need to test and let you know early next week.

**Comment by cjmyers** [comment]
This was a Java 10 issue.  Namely, SBOLDesigner was not using the latest libSBOLj with this fixed.  Its pom file was updated, and it is now working.
